canonical: https://gematik.de/fhir/isik/v2/Basismodul
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Basismodul Stufe 2 2.0.5
name: Implementierungsleitfaden ISiK-Basismodul Stufe 2 2.0.5
status: active
version: "2.0.7"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: ISiK@gematik.de
dependencies:
  de.basisprofil.r4: 1.4.0
  hl7.fhir.r4.core: 4.0.1
  hl7.fhir.extensions.r5: 4.0.1
