canonical: https://gematik.de/fhir/ISiK/
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Basismodul Stufe1 1.0.4
name: Implementierungsleitfaden ISiK-Basismodul Stufe1 1.0.4
status: draft
version: "1.0.4"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: ISiK@gematik.de
dependencies:
  de.basisprofil.r4: 1.2.0-alpha1
  hl7.fhir.r4.core: 4.0.1
