canonical: https://gematik.de/fhir/isik/v3/Basismodul
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
dependencies:
  de.basisprofil.r4: 1.4.0
  hl7.fhir.r4.core: 4.0.1
  hl7.fhir.extensions.r5: 4.0.1
